language: python
python:

  - "3.4.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - psql -c 'create database testdb;' -U postgres
# command to run tests
script: 
- pytest --cov=.
after_success:
- coveralls